### PR TITLE
Fix Styling in Services

### PR DESCRIPTION
**Pull request by SaraVieira**
Please add bugs here

### CODE REVIEW

**Comment by SaraVieira** [comment]
- [ ] mobile version looks nice. Maybe some extra margin/padding around the tech partners(edited)

**Comment by carvil** [comment]
Here are a couple of things Sara:
- [ ] margin-bottom of the 2nd section is a bit too big, can we reduce it? The section with Strategy, Design, etc

screen shot 2018-06-13 at 14 28 30

- [ ] the section with Common client challenges needs some wrapper around iconography so it's all aligned horizontally

screen shot 2018-06-13 at 14 30 50

- [ ] line wraps should probably follow text above

screen shot 2018-06-13 at 14 30 23

**Comment by carvil** [comment]
@SaraVieira the icons on the common client challenges are now left-aligned, should they be centered like before?

**Comment by SaraVieira** [comment]
@carvil That was a mistake on me, this is the design
screen shot 2018-06-13 at 15 03 24

**Comment by carvil** [comment]
@SaraVieira ah, then 👍 

A couple of tweaks on the mobile version:

- [ ] h1 in the header doesn't look right, what do you think?

screen shot 2018-06-13 at 15 07 07

- [ ] the alignment of "common client challenges" in mobile needs an update as well

screen shot 2018-06-13 at 15 07 25

**Pull request merged**
